Import("env")
import os
import re
import shutil
import subprocess
from SCons.Script import COMMAND_LINE_TARGETS

# AI: below section was generated by an AI
# IDE metadata requests do not consume generated UI headers. Avoid running Node
# commands for them so PlatformIO can generate its target-specific index data.
if "__idedata" not in COMMAND_LINE_TARGETS:
    node_ex = shutil.which("node")
    npm_ex = shutil.which("npm")
    project_dir = env.subst("$PROJECT_DIR")

    # Check if Node.js and npm are installed and present in PATH; otherwise abort.
    if node_ex is None or npm_ex is None:
        print('\x1b[0;31;43m' + 'Node.js or npm is not installed or missing from PATH; HTML, CSS, and JS will not be processed. Check https://kno.wled.ge/advanced/compiling-wled/' + '\x1b[0m')
        exit(1)

    # npm ci is an explicit setup step. Reusing installed packages prevents every
    # PlatformIO invocation from deleting and reinstalling node_modules.
    if not os.path.isdir(os.path.join(project_dir, "node_modules")):
        print('\x1b[6;33;42m' + 'Installing node packages' + '\x1b[0m')
        exitCode = subprocess.call([npm_ex, "ci"], cwd=project_dir)
        if exitCode:
            print('\x1b[0;31;43m' + 'npm ci failed; check https://kno.wled.ge/advanced/compiling-wled/' + '\x1b[0m')
            exit(exitCode)

    # Call the bundling script without SCons' command executor.
    ui_env = os.environ.copy()
    # Pass the target-specific banner option to the Node UI generator.
    # This avoids sharing a no-banner UI bundle with builds that do not opt out.
    target_flags = env.GetProjectConfig().get("env:" + env["PIOENV"], "build_flags")
    if any(re.match(r"^\s*-D\s*NO_DEV_BANNER(?:\s|$)", flag) for flag in target_flags):
        ui_env["WLED_NO_DEV_BANNER"] = "1"
    exitCode = subprocess.call([npm_ex, "run", "build"], cwd=project_dir, env=ui_env)
    if exitCode:
        print('\x1b[0;31;43m' + 'npm run build failed; check https://kno.wled.ge/advanced/compiling-wled/' + '\x1b[0m')
        exit(exitCode)
# AI: end
